sudo: false

language: node_js

# Keep empty to use version from .nvmrc
node_js:

install:
  - npm ci

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - npx semantic-release --extends @trustpilot/semanticrelease-config

branches:
  only: master

notifications:
  email: false
