sudo: false

language: node_js

# Keep empty to use version from .nvmrc
node_js:

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - npx semantic-release

branches:
  only: master

notifications:
  email: false
